export const GET_FRUITS = 'GET_FRUITS';
export const ADD_FRUIT = 'ADD_FRUIT';
export const DELETE_FRUIT = 'DELETE_FRUIT';
export const FRUITS_LOADING = 'FRUITS_LOADING';

export const GET_VEGETABLES = 'GET_VEGETABLES';
export const ADD_VEGETABLE = 'ADD_VEGETABLES';
export const DELETE_VEGETABLE = 'DELETE_VEGETABLES';
export const VEGETABLES_LOADING = 'VEGETABLES_LOADING';
